export const tableData = [
  {
    id: 1,
    isChecked: true,
    companyName: "GoWebEz",
    OPM: "Mani",
    projectStatus: "On Track",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 2,
    isChecked: false,
    companyName: "Notified Private DM Limited",
    OPM: "Robert Downey Jr.",
    projectStatus: "On Hold",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 3,
    isChecked: false,
    companyName: "TCS",
    OPM: "Undertaker",
    projectStatus: "Potential Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 4,
    isChecked: false,
    companyName: "Wipro",
    OPM: "Undertaker",
    projectStatus: "At Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 5,
    isChecked: false,
    companyName: "Risolutor Technologies",
    OPM: "Undertaker",
    projectStatus: "Archived",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 6,
    isChecked: false,
    companyName: "Chennai Super Kings",
    OPM: "Undertaker",
    projectStatus: "Archived",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 7,
    isChecked: false,
    companyName: "Mumbai Indians",
    OPM: "Undertaker",
    projectStatus: "At Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 8,
    isChecked: false,
    companyName: "Redmi",
    OPM: "Mani",
    projectStatus: "On Track",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 9,
    isChecked: false,
    companyName: "Real me",
    OPM: "Mani",
    projectStatus: "On Track",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 10,
    isChecked: false,
    companyName: "Samsung",
    OPM: "Robert Downey Jr.",
    projectStatus: "At Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 11,
    isChecked: false,
    companyName: "Apple",
    OPM: "Mani",
    projectStatus: "On Track",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 12,
    isChecked: false,
    companyName: "Yamaha",
    OPM: "Robert Downey Jr.",
    projectStatus: "On Track",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 13,
    isChecked: false,
    companyName: "Luo Yi",
    OPM: "Robert Downey Jr.",
    projectStatus: "At Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
  {
    id: 14,
    isChecked: false,
    companyName: "Yi shin Shi",
    OPM: "Undertaker",
    projectStatus: "Potential Risk",
    lastUpdate: "15 Mar 2021, 12:47PM",
    resources: ["developer", "designer"],
    startDate: "15 May  2021",
    endDate: "15 Aug  2021",
    estimatedPrice: 10.5,
  },
];
